# Generated by Django 5.2.4 on 2025-07-08 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_round', models.PositiveIntegerField(default=0)),
                ('active_combatant_index', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('strength', models.PositiveIntegerField(default=10)),
                ('dexterity', models.PositiveIntegerField(default=10)),
                ('constitution', models.PositiveIntegerField(default=10)),
                ('intelligence', models.PositiveIntegerField(default=10)),
                ('wisdom', models.PositiveIntegerField(default=10)),
                ('charisma', models.PositiveIntegerField(default=10)),
                ('armor_class', models.PositiveIntegerField(default=10)),
                ('max_hp', models.PositiveIntegerField(default=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Combatant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hp', models.IntegerField()),
                ('initiative', models.PositiveIntegerField()),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combatants', to='campaign_manager.encounter')),
                ('enemy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign_manager.enemy')),
            ],
        ),
        migrations.CreateModel(
            name='EncounterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='campaign_manager.combatant')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='campaign_manager.encounter')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_actions', to='campaign_manager.combatant')),
            ],
        ),
        migrations.AddField(
            model_name='enemy',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemies', to='campaign_manager.gamesession'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='campaign_manager.gamesession'),
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('strength', models.PositiveIntegerField(default=10)),
                ('dexterity', models.PositiveIntegerField(default=10)),
                ('constitution', models.PositiveIntegerField(default=10)),
                ('intelligence', models.PositiveIntegerField(default=10)),
                ('wisdom', models.PositiveIntegerField(default=10)),
                ('charisma', models.PositiveIntegerField(default=10)),
                ('armor_class', models.PositiveIntegerField(default=10)),
                ('max_hp', models.PositiveIntegerField(default=10)),
                ('current_hp', models.IntegerField()),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heroes', to='campaign_manager.gamesession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='combatant',
            name='hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign_manager.hero'),
        ),
    ]
