# Generated by Django 5.2.4 on 2025-07-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='alignment',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='background',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='char_class',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='char_subclass',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='level',
        ),
    ]
