# Generated by Django 5.2.4 on 2025-07-09 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0002_remove_enemy_alignment_remove_enemy_background_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combatant',
            name='enemy',
        ),
        migrations.RemoveField(
            model_name='combatant',
            name='hero',
        ),
        migrations.AddField(
            model_name='combatant',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combatant',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
